// LOCAL TESTING COMMAND
## GET ALL CONTACTS 
GET http://localhost:3000/contacts/ 

### GET CONTACT BY ID 1
GET http://localhost:3000/contacts/69033a4c07767cb9e7ba3f51

### GET CONTACT BY ID 2
GET http://localhost:3000/contacts/69033a4c07767cb9e7ba3f52

### GET CONTACT BY ID 3
GET http://localhost:3000/contacts/69033a4c07767cb9e7ba3f53

### CREATE CONTACT
POST http://localhost:3000/contacts/ HTTP/1.1
content-type: application/json

{
    "firstName": "Prince",
    "lastName": "Ojera",
    "email": "prince860@gmail.com",
    "favoriteColor": "Magenta",
    "birthday": "16/02/2012"
}

### UPDATE CONTACT
PUT http://localhost:3000/contacts/690f668c1e145137bf440e99 HTTP/1.1
content-type: application/json

{
   "firstName": "Ochan",
    "lastName": "Ojera",
    "email": "ochan@gmail.com",
    "favoriteColor": "Cyan",
    "birthday": "16/08/1995" 
}

### DELETE CONTACT  
DELETE http://localhost:3000/contacts/690f668c1e145137bf440e99

// PRODUCTION TESTING COMMAND
### GET ALL CONTACTS
GET https://cse341-project1-y59y.onrender.com/contacts/

### GET CONTACT BY ID 1
GET https://cse341-project1-y59y.onrender.com/contacts/69033a4c07767cb9e7ba3f51

### GET CONTACT BY ID 2
GET https://cse341-project1-y59y.onrender.com/contacts/69033a4c07767cb9e7ba3f52

### GET CONTACT BY ID 3
GET https://cse341-project1-y59y.onrender.com/contacts/69033a4c07767cb9e7ba3f53



